### ISSUE TITLE
Add option to disable deriving Deref

### ISSUE THREAD

**Issue by null-dev** [loliGothicK/deriving_via#166]
Hello! First of all, amazing crate, I have been looking for something like this for a long time!

Would you consider adding an option to disable deriving Deref? Many times I want to derive only specific traits and do not want to derive Deref.

**Comment by loliGothicK** [comment]
@null-dev 
Hello. Thank you for your suggestion.
Do you want a macro that only provides _Generalised Newtype Deriving_?

**Comment by null-dev** [comment]
Thanks for the link to `derive_more`, I was not aware of that crate! I guess I am looking for generalized newtype deriving but I may need to think about my use case more. Feel free to close if you think it isn't suitable for this crate.
